version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    command:
      - start-dev --log-console-color true
    environment:
      KC_DB_VENDOR: POSTGRES
      KC_DB_ADDR: postgres
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      # Uncomment the line below if you want to specify JDBC parameters.
      # The parameter below is just an example, and it shouldn't be used in production without knowledge.
      # It is highly recommended that you read the PostgresSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "7688:8080"
    depends_on:
      - postgres

  app:
    depends_on:
      - mysqldb
#    build:
#      context: ./
#      dockerfile: Dockerfile
    build: ./audit-request-management
    restart: on-failure
    env_file: ./.env
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  postgres_data:
    driver: local