server:
  port: 8888
# this config server connects to the git url given url
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sikindar-j/arm-config-store.git



